"""End-to-end demo: train the tiny GPT on the bundled Shakespeare excerpt,
save a loss curve, and print 'before vs after' samples for the README.

Run it from the repo root:

    python scripts/train_demo.py

Outputs:
    assets/loss_curve.png     the train/val loss over training
    assets/sample_before.txt  text generated by the UNTRAINED model
    assets/sample_after.txt   text generated by the TRAINED model

Everything is seeded, so re-running reproduces the same curve and samples.
Kept small enough to finish in a couple of minutes on a CPU.
"""

from __future__ import annotations

import os

import matplotlib

matplotlib.use("Agg")  # headless backend: render straight to a PNG file
import matplotlib.pyplot as plt
import torch

from glassbox import GPT, GPTConfig, generate
from glassbox.data import TextData
from glassbox.train import TrainConfig, set_seed, train

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ASSETS = os.path.join(ROOT, "assets")


def sample_text(model: GPT, data: TextData, n_tokens: int, seed: int) -> str:
    """Generate n_tokens of text starting from a newline, decoded to a string."""
    gen = torch.Generator().manual_seed(seed)
    start = data.tokenizer.encode_to_tensor("\n").view(1, 1)   # (1, 1)
    out = generate(model, start, max_new_tokens=n_tokens,
                   temperature=0.8, top_k=20, generator=gen)   # (1, 1+n)
    return data.tokenizer.decode(out[0].tolist())


def main() -> None:
    os.makedirs(ASSETS, exist_ok=True)
    set_seed(1337)

    # --- data & model ---
    block_size = 128
    data = TextData(block_size=block_size, device="cpu")
    cfg = GPTConfig(
        vocab_size=data.vocab_size,
        block_size=block_size,
        n_layer=4, n_head=4, n_embd=128,
        dropout=0.1,
    )
    model = GPT(cfg)
    print(f"model has {model.num_params()/1e6:.2f}M parameters, vocab={data.vocab_size}")

    # --- BEFORE: sample from the untrained model ---
    before = sample_text(model, data, n_tokens=400, seed=0)
    with open(os.path.join(ASSETS, "sample_before.txt"), "w", encoding="utf-8") as f:
        f.write(before)
    print("\n===== BEFORE TRAINING (untrained model) =====\n")
    print(before)

    # --- train ---
    tcfg = TrainConfig(max_iters=3000, batch_size=32, eval_interval=250,
                       learning_rate=3e-4, device="cpu")
    history = train(model, data, tcfg)

    # --- AFTER: sample from the trained model ---
    after = sample_text(model, data, n_tokens=400, seed=0)
    with open(os.path.join(ASSETS, "sample_after.txt"), "w", encoding="utf-8") as f:
        f.write(after)
    print("\n===== AFTER TRAINING =====\n")
    print(after)

    # --- loss curve ---
    iters = [h[0] for h in history]
    tr = [h[1] for h in history]
    va = [h[2] for h in history]
    plt.figure(figsize=(7, 4.5))
    plt.plot(iters, tr, label="train", linewidth=2)
    plt.plot(iters, va, label="val", linewidth=2)
    plt.xlabel("iteration")
    plt.ylabel("cross-entropy loss")
    plt.title("Glassbox — training on tiny Shakespeare")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    out_png = os.path.join(ASSETS, "loss_curve.png")
    plt.savefig(out_png, dpi=120)
    print(f"\nsaved loss curve -> {out_png}")
    print(f"final: train {tr[-1]:.4f} | val {va[-1]:.4f}")


if __name__ == "__main__":
    main()
